name: Deploy to Lambda

on:
  push:
    branches: [ main, sentiment-analysis ]

jobs:
  upload_deps:
    if: github.repository != 'jaARke/discord-lambda-py'
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Upload dependencies to S3
        env:
          release_bucket: acestockbot
          release_bucket_uri: s3://acestockbot
          release_id: deps.zip
          release_layer: ACEBot_Dependencies
          function_name: ACEBot_handler
          APP_ID: ${{ secrets.APP_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          # Package up the dependencies
          mkdir -p python/lib/python3.9/site-packages

          env > env_vars && docker run -v "$PWD":/var/task "public.ecr.aws/sam/build-python3.9" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.9/site-packages/ \
          && PYTHONPATH=python/lib/python3.9/site-packages python InteractionHandlerPickler.py; exit --env-file ./env_vars"

          zip --quiet -r $release_id python InteractionHandler.pickle

          echo "Uploading $release_id to $release_bucket_uri"
          aws s3 cp $release_id $release_bucket_uri
          aws lambda publish-layer-version --layer-name $release_layer  --content S3Bucket=$release_bucket,S3Key=$release_id --compatible-runtimes python3.9

          # Get the previous layer version number
          prev_layer_version=$(aws lambda list-layer-versions --layer-name $release_layer --query 'LayerVersions[1].Version' --output text)

          # Delete the previous layer version
          aws lambda delete-layer-version --layer-name $release_layer --version-number $prev_layer_version

          # Get the new layer version ARN
          layer_arn=$(aws lambda list-layer-versions --layer-name $release_layer --query 'LayerVersions[0].LayerVersionArn' --output text)

          # Update the lambda function to use the new layer
          aws lambda update-function-configuration --function-name $function_name --layers $layer_arn
  
  upload_source:
    if: github.repository != 'jaARke/discord-lambda-py'
    name: Upload Source to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
        
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: ACEBot_handler
          zip_file: bundle.zip